### ISSUE TITLE
something wrong with the masses of the tanks?

### ISSUE THREAD

**Issue by kitoma** [BobPalmer/SoundingRockets#14]
Looks to me like the tank dry/wet masses are higher than intended, shows ingame as 0.26t wet for the SR-35A (with about 0.11t fuel?), and 1.35t wet for the SR-625A (including 0.5t fuel). So basically both tanks have a dry mass above the fuel contents mass, which is kind of unexpected.
(And for the 625 tank, even if one changes the dry weight from the current 0.85t to 0.35t, it's still considerably "worse" than the roughly equivalent stock T100 tank, which has the same amount of fuel but only 62.5kg dry weight. But without further information I would assume that could be a design choice based on the "early game" nature of these tanks.)

**Comment by BobPalmer** [comment]
Updated in next release to be inline with the oscar tanks (FYI your T100 tank numbers are way off - the dry mass of the T100 is 0.5625)

**Comment by kitoma** [comment]
Hmm? In my book, 0.5625t minus half a ton of fuel (45LF+55LO) is 0.0625t, i.e. 62.5kg :)

Anyway, thanks for fixing it, looks good now.
