### ISSUE TITLE
(0.2.0 PRE) Experiment payloads have wrong model

### ISSUE THREAD

**Issue by Nitrous0xide** [BobPalmer/SoundingRockets#3]
Minor detail, but the filenames of the part models don't match up with the names you've given to the parts themselves. Payload01 (meterology) has the model for Payload03 (mini-science) and vice-versa. Same issue with 2 and 4. 

Assets/SR_Payload01.mu should be renamed Assets/SR_Payload03.mu
Assets/SR_Payload03.mu should be renamed Assets/SR_Payload01.mu
... or really however the models work, I only changed my config files for the time being ;)

**Comment by BobPalmer** [comment]
Fixed in next release
