### ISSUE TITLE
Mod Incompatibility

### ISSUE THREAD

**Issue by VaPaL** [BobPalmer/SoundingRockets#44]
Good night RoverDude,

I found a incompatibility with Sounding Rockets and Surface Experiment Pack (http://forum.kerbalspaceprogram.com/index.php?/topic/77858-11-surface-experiment-pack-eva-science-for-kiskas-v14-2742016/).

When both are installed none of the Sounding Rockets experiments work. I can't even right click on them during a flight. Neither Surface Experiments Pack experiments work.

Best regards,
VaPaL

**Comment by BobPalmer** [comment]
This should be sorted - if it is still an issue after the next release, let me
