### ISSUE TITLE
Remote Tech config

### ISSUE THREAD

**Issue by UnanimousCoward** [BobPalmer/SoundingRockets#5]
Here's an MM config that adds a passive antenna to the avionics package:

// RemoteTech_SoundingRockets
// This is free and unencumbered software released into the public domain.
// All the code from RemoteTech is in GPLv2

@PART[SR_ProbeCore]:HAS[!MODULE[ModuleSPU],!MODULE[ModuleRTAntennaPassive]]:NEEDS[RemoteTech,UmbraSpaceIndustries]:AFTER[UmbraSpaceIndustries]:FINAL
{
	%MODULE[ModuleSPU] 
	{
	}
	%MODULE[ModuleRTAntennaPassive]	
	{
		%TechRequired = start
		%OmniRange = 100000
		%TRANSMITTER 
		{
			%PacketInterval = 0.3
			%PacketSize = 2
			%PacketResourceCost = 15.0
		}
	}
}
@PART[RTPassiveAntennaTech]:NEEDS[RemoteTech,UmbraSpaceIndustries]:AFTER[RemoteTech]:FINAL
{
	@TechRequired = start
}

**Comment by futrtrubl** [comment]
This doesn't add the passive antenna at the start like you think.
