### ISSUE TITLE
Grid fins should not generate lift while retracted

### ISSUE THREAD

**Issue by jd284** [BobPalmer/SoundingRockets#62]
See also http://forum.kerbalspaceprogram.com/index.php?/topic/92434-12-sounding-rockets-start-small-dream-big-050/&do=findComment&comment=2835144

Currently the grid fins generate control lift (yellow arrows with F12) and much drag even when retracted. This means the only way to use them to control a landing first stage is by hiding them in a fairing during ascent.

If possible please make it so that they do not generate lift forces (and much less drag) when retracted.

**Comment by BobPalmer** [comment]
Fixed next release
