### ISSUE TITLE
Disable ability to re-run science experiments?

### ISSUE THREAD

**Issue by basedrifter** [BobPalmer/SoundingRockets#7]
I started a new career recently and have been playing around with sounding rocket parts, specifically the Meteorological, Aeronomical, Materials, and Engineering experiments. It seems to me like they would be better suited to be one time use only experiments like the Mystery Goo.

With all four experiments being re-runnable, I was able to get quite a large amount of science just orbiting around Kerbin, Minmus, the Mun, and Duna from all the various biomes. Seemed a little too easy to spam these experiments.

**Comment by BobPalmer** [comment]
This has been corrected
