### ISSUE TITLE
Grid fins should not generate lift while retracted

### ISSUE THREAD

**Issue by jd284** [BobPalmer/SoundingRockets#72]
Creating new issue because I can't reopen #62.

Unfortunately the issue wasn't fixed in the latest release (SR 0.5.5 USITools 0.8.9).

The ModuleLiftingSurface control interface disappears when the grid fins are stowed, but apparently it isn't enough to disable the module. The yellow lift arrows still appear just like in the old screenshot at http://forum.kerbalspaceprogram.com/index.php?/topic/92434-12-sounding-rockets-start-small-dream-big-050/&do=findComment&comment=2835144.

My testing has indicated that the only way to remove the yellow arrows was to rename the ModuleLiftingSurface to an invalid module name (or remove it entirely).

I'm not sure if there's a way to rename a module or some other way to _really_ deactivate it (can a module be removed in flight?), or if this is a stock bug that it ignores the "isEnabled" property and generates lift anyway. If the latter feel free to close the issue and I'll make a ticket on the stock tracker.

**Comment by jd284** [comment]
As a side note, maybe it's possible to make the module somehow think that the part is inside a fairing when stowed? Would part.ShieldedFromAirstream work maybe?

**Comment by BobPalmer** [comment]
This should be sorted in the current release.
