### ISSUE TITLE
Mini Decoupler odds and ends

### ISSUE THREAD

**Issue by futrtrubl** [BobPalmer/SoundingRockets#8]
The mini decoupler doesn't have 'fuelCrossFeed = False' like stock decouplers so unfortunately engines steal fuel from later stages. This also causes issues with mechjeb's dV calculations.
This part is more pedantic. It's called a decoupler buts acts like a separator. IE usually decouplers just eject from the top but this ejects at both nodes.
This is with the dev version 0.2.0 pre of course.

**Comment by BobPalmer** [comment]
Fixed both in next release
